import { setRequestLocale } from "next-intl/server";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms & Conditions | Janta Medicare",
  description: "Terms and Conditions for Janta Medicare",
};

export default async function TermsAndConditionsPage({
  params,
}: {
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  setRequestLocale(locale);

  return (
    <div className="container py-12 md:py-20">
      <div className="mx-auto max-w-4xl prose prose-slate prose-headings:font-heading prose-headings:text-primary-deep prose-a:text-primary hover:prose-a:text-primary-strong">
        <h1>Terms & Conditions</h1>
        <p className="text-sm text-muted">Last Updated: August 2026</p>

        <p>
          Welcome to Janta Medicare. By accessing or using our website, you agree to comply with and be bound by the following terms and conditions.
        </p>

        <div className="rounded-xl border-l-4 border-accent bg-accent-soft p-5 my-8">
          <h2 className="mt-0 text-accent font-bold">Important Medical Disclaimer</h2>
          <p className="mb-0 text-accent-strong">
            The content on this website, including but not limited to text, graphics, images, prices, and information generated by the AI Chatbot, is for informational purposes only. It is <strong>NOT</strong> a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition. Never disregard professional medical advice or delay in seeking it because of something you have read on this website.
          </p>
        </div>

        <h2>1. AI Chatbot Limitations</h2>
        <p>
          Our platform utilizes Artificial Intelligence (AI) to provide quick information regarding medicine prices and pathology test rates. 
        </p>
        <ul>
          <li>The AI is an automated system and can occasionally generate incorrect or hallucinatory responses.</li>
          <li>You must verify all critical information, especially regarding medicine dosages, availability, and test details, directly with our pharmacy staff.</li>
          <li>In the event of a medical emergency, do not rely on the AI. Call your local emergency services immediately.</li>
        </ul>

        <h2>2. Pricing and Availability</h2>
        <p>
          While we strive to keep our &quot;Janta Prices&quot; and MRPs updated in real-time, all prices are subject to change without prior notice. The final billed amount at our physical stores may vary slightly due to tax updates or batch differences. Product availability is subject to physical stock at our Shibpur Main Hub.
        </p>

        <h2>3. Intellectual Property</h2>
        <p>
          All content, logos, and digital assets on this website are the property of Janta Medicare LLP. You may not reproduce, distribute, or exploit this content for commercial purposes without explicit permission.
        </p>

        <h2>4. Limitation of Liability</h2>
        <p>
          Janta Medicare LLP, its directors, employees, and software developers (including Zenith Open Source Projects) shall not be held liable for any direct, indirect, incidental, or consequential damages resulting from the use or inability to use this website, including reliance on any information provided by the AI chatbot.
        </p>

        <h2>5. Governing Law</h2>
        <p>
          These terms and conditions are governed by and construed in accordance with the laws of India. Any disputes relating to these terms and conditions will be subject to the exclusive jurisdiction of the courts of Howrah, West Bengal.
        </p>
      </div>
    </div>
  );
}
