create table if not exists public.medicines (
  id bigint primary key generated by default as identity,
  s_no integer not null,
  medicine_name text not null,
  selling_price numeric not null,
  pack_size text not null,
  mrp numeric not null
);

create table if not exists public.patient_rates (
  id bigint primary key generated by default as identity,
  sl_no integer not null,
  test_name text not null,
  jm_rate text not null,
  vail_name text
);

-- Enable RLS and grant public read access
alter table public.medicines enable row level security;
alter table public.patient_rates enable row level security;

create policy "medicines public read" on public.medicines for select to anon, authenticated using (true);
create policy "patient_rates public read" on public.patient_rates for select to anon, authenticated using (true);

-- Allow service_role full access
grant all on public.medicines to service_role;
grant all on public.patient_rates to service_role;
