-- 1. Create medicine_batches table
CREATE TABLE IF NOT EXISTS public.medicine_batches (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    medicine_id BIGINT NOT NULL REFERENCES public.medicines(id) ON DELETE CASCADE,
    barcode TEXT UNIQUE,
    batch_number TEXT,
    expiry_date TEXT,
    buying_price NUMERIC,
    selling_price NUMERIC,
    mrp NUMERIC,
    purchase NUMERIC,
    sale NUMERIC,
    stock NUMERIC NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable RLS for batches
ALTER TABLE public.medicine_batches ENABLE ROW LEVEL SECURITY;
CREATE POLICY "medicine_batches public read" ON public.medicine_batches FOR SELECT USING (true);
CREATE POLICY "medicine_batches admin all" ON public.medicine_batches USING (auth.role() = 'authenticated' OR auth.role() = 'service_role');
GRANT ALL ON public.medicine_batches TO service_role;
GRANT ALL ON public.medicine_batches TO authenticated;
GRANT SELECT ON public.medicine_batches TO anon;

-- 2. Migrate existing data from medicines to medicine_batches (Skipped for local since columns don't exist)
-- In live DB this was run manually or had different schema.

-- 3. Drop migrated columns from medicines
ALTER TABLE public.medicines 
    DROP COLUMN IF EXISTS batch_number,
    DROP COLUMN IF EXISTS expiry_date,
    DROP COLUMN IF EXISTS buying_price,
    DROP COLUMN IF EXISTS selling_price,
    DROP COLUMN IF EXISTS mrp,
    DROP COLUMN IF EXISTS purchase,
    DROP COLUMN IF EXISTS sale,
    DROP COLUMN IF EXISTS quantity;

-- 4. Create invoices table
CREATE TABLE IF NOT EXISTS public.invoices (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    invoice_no TEXT UNIQUE NOT NULL,
    patient_name TEXT,
    doctor_name TEXT,
    subtotal NUMERIC NOT NULL DEFAULT 0,
    gst_total NUMERIC NOT NULL DEFAULT 0,
    discount NUMERIC NOT NULL DEFAULT 0,
    net_amount NUMERIC NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'completed' CHECK (status IN ('completed', 'cancelled')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable RLS for invoices
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;
CREATE POLICY "invoices admin all" ON public.invoices USING (auth.role() = 'authenticated' OR auth.role() = 'service_role');
GRANT ALL ON public.invoices TO service_role;
GRANT ALL ON public.invoices TO authenticated;

-- 5. Create invoice_items table
CREATE TABLE IF NOT EXISTS public.invoice_items (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    invoice_id BIGINT NOT NULL REFERENCES public.invoices(id) ON DELETE CASCADE,
    batch_id BIGINT REFERENCES public.medicine_batches(id),
    quantity NUMERIC NOT NULL,
    rate NUMERIC NOT NULL,
    gst_percent NUMERIC NOT NULL,
    gst_amount NUMERIC NOT NULL,
    amount NUMERIC NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable RLS for invoice_items
ALTER TABLE public.invoice_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "invoice_items admin all" ON public.invoice_items USING (auth.role() = 'authenticated' OR auth.role() = 'service_role');
GRANT ALL ON public.invoice_items TO service_role;
GRANT ALL ON public.invoice_items TO authenticated;

-- 6. RPC Function for POS Checkout (Atomic Stock Reduction & Invoice Creation)
CREATE OR REPLACE FUNCTION public.create_invoice(
    p_invoice_no TEXT,
    p_patient_name TEXT,
    p_doctor_name TEXT,
    p_subtotal NUMERIC,
    p_gst_total NUMERIC,
    p_discount NUMERIC,
    p_net_amount NUMERIC,
    p_items JSONB -- Array of {batch_id, quantity, rate, gst_percent, gst_amount, amount}
) RETURNS BIGINT AS $$
DECLARE
    v_invoice_id BIGINT;
    v_item JSONB;
    v_batch_id BIGINT;
    v_quantity NUMERIC;
BEGIN
    -- Insert invoice
    INSERT INTO public.invoices (invoice_no, patient_name, doctor_name, subtotal, gst_total, discount, net_amount, status)
    VALUES (p_invoice_no, p_patient_name, p_doctor_name, p_subtotal, p_gst_total, p_discount, p_net_amount, 'completed')
    RETURNING id INTO v_invoice_id;

    -- Process each item
    FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
    LOOP
        v_batch_id := (v_item->>'batch_id')::BIGINT;
        v_quantity := (v_item->>'quantity')::NUMERIC;

        -- Check and deduct stock atomically
        UPDATE public.medicine_batches
        SET stock = stock - v_quantity
        WHERE id = v_batch_id AND stock >= v_quantity;

        IF NOT FOUND THEN
            RAISE EXCEPTION 'Insufficient stock for batch_id %', v_batch_id;
        END IF;

        -- Insert line item
        INSERT INTO public.invoice_items (invoice_id, batch_id, quantity, rate, gst_percent, gst_amount, amount)
        VALUES (
            v_invoice_id, 
            v_batch_id, 
            v_quantity, 
            (v_item->>'rate')::NUMERIC, 
            (v_item->>'gst_percent')::NUMERIC, 
            (v_item->>'gst_amount')::NUMERIC, 
            (v_item->>'amount')::NUMERIC
        );
    END LOOP;

    RETURN v_invoice_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
GRANT EXECUTE ON FUNCTION public.create_invoice TO authenticated, service_role;

-- 7. RPC Function for Invoice Cancellation (Atomic Stock Return)
CREATE OR REPLACE FUNCTION public.cancel_invoice(p_invoice_id BIGINT) 
RETURNS BOOLEAN AS $$
DECLARE
    v_status TEXT;
    v_item RECORD;
BEGIN
    -- Check current status
    SELECT status INTO v_status FROM public.invoices WHERE id = p_invoice_id FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Invoice not found';
    END IF;
    IF v_status = 'cancelled' THEN
        RAISE EXCEPTION 'Invoice is already cancelled';
    END IF;

    -- Update invoice status
    UPDATE public.invoices SET status = 'cancelled', updated_at = NOW() WHERE id = p_invoice_id;

    -- Return stock for all items
    FOR v_item IN SELECT batch_id, quantity FROM public.invoice_items WHERE invoice_id = p_invoice_id
    LOOP
        IF v_item.batch_id IS NOT NULL THEN
            UPDATE public.medicine_batches
            SET stock = stock + v_item.quantity, updated_at = NOW()
            WHERE id = v_item.batch_id;
        END IF;
    END LOOP;

    RETURN TRUE;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
GRANT EXECUTE ON FUNCTION public.cancel_invoice TO authenticated, service_role;
